name: uni_credit
description: A new Flutter project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  file_picker: ^5.2.2
  auto_route: ^7.4.0
  shared_preferences: ^2.0.0-nullsafety
  dio: ^5.0.1
  dropdown_button2: ^2.1.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  get_it: ^7.6.4
  provider: ^6.1.1
  firebase_core: ^2.14.0
  introduction_screen: ^3.1.9
  timelineview: ^1.0.2

  request_states:
    path: ../../itec_integrated_flutter/request_states

  flexible_structures:
    path: ../../itec_integrated_flutter/flexible_structures

  common_extensions:
    path: ../../itec_integrated_flutter/common_extensions

  form_components:
    path: ../../form_components

  #authentication:
  #  path: ../../flutter_generic_routes/authentication
  #dev_presenting:
  #  path: ../../flutter_generic_routes/dev_presenting
  #flutter_localization: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  auto_route_generator: ^7.1.1
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
  generate: true

  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
